# 1.1 PyTorch 中的数据操作

在PyTorch中，`torch.Tensor`是存储和变换数据的主要工具。`Tensor`和`NumPy`的多维数组非常类似。然而，`Tensor`提供GPU计算和自动求梯度等更多功能，这些使`Tensor`更加适合深度学习。
  
> `tensor`这个单词一般可译作“张量”，张量可以看作是一个多维数组。标量可以看作是0维张量，向量可以看作1维张量，矩阵可以看作是二维张量

## 1.1.1 创建 Tensor

In [1]:
import torch

In [2]:
# 创建一个 5*3 的未初始化的 tensor
x = torch.empty(5, 3)
print(x)

tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 9.7346e-39, 1.0745e-38]])


In [3]:
# 创建一个 5*3 的随机初始化的 tensor
x = torch.rand(5, 3)
print(x)

tensor([[0.1348, 0.8399, 0.9473],
        [0.1860, 0.6973, 0.9763],
        [0.4853, 0.5633, 0.9089],
        [0.2912, 0.1038, 0.4749],
        [0.2641, 0.9814, 0.9953]])


In [4]:
# 创建一个 5x3 的long型全0的 tensor
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 直接根据数据创建
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


通过现有的`tensor`来创建，这种方法会默认重用现有`tensor`的一些属性，如数据类型，除非自定义数据类型

In [6]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1383, -1.1743, -0.1557],
        [-0.2422, -0.6329,  0.1242],
        [ 0.0502,  0.0770, -0.5180],
        [-0.4676, -0.3543,  0.2965],
        [ 0.1055,  1.1650,  0.2480]])


通过`shape`和`size()`来获取`tensor`的形状，返回的`torch.Size`是一个tuple，支持所有tuple的操作

In [8]:
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


## 1.1.2 Tensor 操作
### 算数操作

In [9]:
# 加法形式一
y = torch.rand(5, 3)
print(x + y)

# 加法形式二
print(torch.add(x, y))

tensor([[ 0.7542, -0.5960,  0.1433],
        [ 0.0424,  0.1709,  1.1144],
        [ 0.3259,  1.0141,  0.3707],
        [ 0.4122,  0.5851,  0.3646],
        [ 0.4682,  1.2478,  0.5752]])
tensor([[ 0.7542, -0.5960,  0.1433],
        [ 0.0424,  0.1709,  1.1144],
        [ 0.3259,  1.0141,  0.3707],
        [ 0.4122,  0.5851,  0.3646],
        [ 0.4682,  1.2478,  0.5752]])


In [10]:
# 指定输出
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.7542, -0.5960,  0.1433],
        [ 0.0424,  0.1709,  1.1144],
        [ 0.3259,  1.0141,  0.3707],
        [ 0.4122,  0.5851,  0.3646],
        [ 0.4682,  1.2478,  0.5752]])


In [11]:
# 加法形式三，inplace
y.add_(x)
print(y)

tensor([[ 0.7542, -0.5960,  0.1433],
        [ 0.0424,  0.1709,  1.1144],
        [ 0.3259,  1.0141,  0.3707],
        [ 0.4122,  0.5851,  0.3646],
        [ 0.4682,  1.2478,  0.5752]])


### 索引
可以使用类似`Numpy`的索引操作来访问`Tensor`的一部分，需要注意的是：索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。

In [12]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 原 Tensor 也被修改了

tensor([ 1.1383, -0.1743,  0.8443])
tensor([ 1.1383, -0.1743,  0.8443])


### 改变形状
使用`view()`来改变`Tensor`的形状，`view()`返回的新`Tensor`和原`Tensor`虽然可能有不同的size，但依旧共享 data，更改其中的一个，另外一个也会跟着改变。(顾名思义，view仅仅是改变了对这个张量的观察角度，内部数据并未改变)

In [13]:
y = x.view(15)
z = x.view(-1, 5) # -1所指的维度会根据其他维度自动计算出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [14]:
x += 1
print(x)
print(y) # y 也加了一

tensor([[2.1383, 0.8257, 1.8443],
        [0.7578, 0.3671, 1.1242],
        [1.0502, 1.0770, 0.4820],
        [0.5324, 0.6457, 1.2965],
        [1.1055, 2.1650, 1.2480]])
tensor([2.1383, 0.8257, 1.8443, 0.7578, 0.3671, 1.1242, 1.0502, 1.0770, 0.4820,
        0.5324, 0.6457, 1.2965, 1.1055, 2.1650, 1.2480])


如果我们想返回一个真正新的副本（即不共享`data`内存）该怎么办呢？`Pytorch`还提供了一个`reshape()`可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用`clone`创造一个副本然后再使用`view`

In [15]:
x_copy = x.clone().view(15)
x -= 1
print(x)
print(x_copy)

tensor([[ 1.1383, -0.1743,  0.8443],
        [-0.2422, -0.6329,  0.1242],
        [ 0.0502,  0.0770, -0.5180],
        [-0.4676, -0.3543,  0.2965],
        [ 0.1055,  1.1650,  0.2480]])
tensor([2.1383, 0.8257, 1.8443, 0.7578, 0.3671, 1.1242, 1.0502, 1.0770, 0.4820,
        0.5324, 0.6457, 1.2965, 1.1055, 2.1650, 1.2480])


使用`clone`的一个好处是会被记录计算图中，即梯度回传到副本时也会传到原`Tensor`

另一个常用的函数就是`item()`，可以将一个标量`Tensor`转换为一个`python number`

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4117])
-0.41168665885925293


## 1.1.3 广播机制
当两个形状不同的`Tensor`按元素运算时会触发广播机制：先适当复制元素使这两个`Tensor`形状相同后再按元素运算

In [18]:
x = torch.arange(1, 3).view(1, 2)
print(x)

y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 1.1.4 运算的内存开销
使用索引不会开辟新的内存，而像`y=x+y`这样的运算会开辟新的内存，例如

In [26]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


如果想指定结果到原来的`y`的内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们把`x + y`的结果通过`[:]`写进`y`对应的内存中

In [25]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before) # True

True


## 1.1.5 tensor 和 numpy 相互转换
用`numpy()`和`from_numpy()`将`Tensor`和`NumPy`中的数组相互转换。但是需要注意的一点是： 这两个函数所产生的的`Tensor`和`NumPy`中的数组共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！

### `tensor`转`numpy`

In [27]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### `numpy`转`tensor`

In [28]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


此外上面提到还有一个常用的方法就是直接用`torch.tensor()`将`NumPy`数组转换成`Tensor`，需要注意的是该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存

In [29]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
